### ISSUE TITLE
Installing on PineBook Pro running manjaro

### ISSUE THREAD

**Issue by 19eleven** [futurejones/balena-etcher-arm#2]
I just got the PineBook Pro that comes with manjaro and I'd like to install etcher, but it looks like these instructions are for the debian OS...

**Comment by futurejones** [comment]
Unfortunately this version of balena-etcher is only for  Debian/Ubuntu. I would suggest asking on Manjaro or Balena forums to see if anybody else has a version for Manjaro arm64.

**Comment by 19eleven** [comment]
The search continues, thank you.
