### ISSUE TITLE
update for raspbian

### ISSUE THREAD

**Issue by saulinternet** [futurejones/balena-etcher-arm#4]
Hi! could you release an update for current raspbian, please? Many thanks

**Comment by gounthar** [comment]
Hi,

While waiting for an official release, you could always try [mine](https://github.com/gounthar/balena-etcher-arm/releases/tag/v1.7.8).
I am currently rebuilding a newer one.

**Comment by futurejones** [comment]
@saulinternet, I have just released v1.7.9
